### ISSUE TITLE
By default, align headline text for section with content

### ISSUE THREAD

**Issue by flyingwalrus93** [flyingwalrus93/walrus-portfolio-nextjs#3]
Or generally propose a cocept for a text content definition?

![grafik](https://user-images.githubusercontent.com/116503577/210376132-d833e845-1079-43c0-af53-a9f4e327c100.png)

![grafik](https://user-images.githubusercontent.com/116503577/210376405-77421c55-8696-4c63-b456-f34fbe3ad184.png)

**Comment by DerTimonius** [comment]
Similar to #2
