### ISSUE TITLE
Do we need a (currently pointless) fullscreen button?

### ISSUE THREAD

**Issue by flyingwalrus93** [flyingwalrus93/walrus-portfolio-nextjs#5]
![grafik](https://user-images.githubusercontent.com/116503577/210377125-f43eef2b-55e8-4c31-a4fa-c2b36fb7962f.png)

**Comment by DerTimonius** [comment]
Where exactly is this button? I guess in the `Single Picture View`?
If so, then it's coming from the library we're using. Would have to look into it if there is an option to disable it but I doubt there is...
